def list_the_planets():
    planets = [
        "Allosimanius Syneca",
        "Argabuthon",
        "Arkintoofle Minor",
        "Asbleg",
        "Asgard",
        "Bartledan",
        "Betelgeuse V",
        "Betelgeuse VII",
        "Bethselamin",
        "Blagulon Kappa",
        "Brontitall",
        "Broop Kidron Thirteen",
        "Burphon XII",
        "Damogran",
        "Dangrabad Beta",
        "Earth",
        "Eroticon VI",
        "Fallia",
        "Flargathon",
        "Frogstar World A",
        "Frogstar World B",
        "Frogstar World C",
        "Gagrakacka",
        "Golgafrincham",
        "Han Wavel",
        "Happi-Werld III",
        "Hawalius",
        "Jaglan Beta",
        "Jajazikstak",
        "Jikthroom Beta",
        "Joltrast 3",
        "Kakrafoon Kappa",
        "Kria",
        "Krikkit",
        "Lamuella",
        "Lazgar Beta",
        "Magrathea",
        "Nano",
        "Nephologia",
        "Neptune",
        "NowWhat",
        "Oglaroon",
        "Pluto",
        "Poghril",
        "Preliumtarn",
        "Rupert",
        "Santraginus V",
        "Saquo-Pilia Hensha",
        "Sesefras Magna",
        "Sqornshellous Zeta",
        "Striterax",
        "Stug",
        "Traal",
        "Ursa Minor Beta",
        "Viltvodle VI",
        "Vogsphere",
        "Xaxrax Sigma"
    ]
    return planets
